### ISSUE TITLE
Implement exit game on main menu scene

### ISSUE THREAD

**Issue by ilmercu** [Option7-OctoPuss/MeetYourTesterGame#102]
# US: Exit the game [#34](https://github.com/Option7-OctoPuss/MeetYourTesterGame/issues/34)

## PREREQUISITES:
1. main menu scene
2. the confirmation popup

## GODOT:
1. Implement the logic behind the exit the game texture button in the main menu
    1. emit a signal notifying the game to spawn the confirmation prompt

## BOUNDARIES:
1. What this task handles is the implementation, by emitting a signal, of the logic of the exit the game button

## OUTCOMES:
1. Emit exit the game signal

**Comment by Husam-Jenidi** [comment]
almost done, needs some minor edits to adding the scene
