### ISSUE TITLE
Create exit the game prompt UI

### ISSUE THREAD

**Issue by ilmercu** [Option7-OctoPuss/MeetYourTesterGame#103]
# US: Exit the game [#34](https://github.com/Option7-OctoPuss/MeetYourTesterGame/issues/34)

## PREREQUISITES:
None

## FIGMA:
1. Create the UI of exit the game prompt which is shown on different game scenarios (main menu, gameplay, other in-game scene)

## BOUNDARIES:
1. What this task handles is the creation of the UI of the exit the game prompt

## OUTCOMES:
1. Prompt UI

**Comment by Husam-Jenidi** [comment]
press ESC to show the menu with option to exit

**Comment by Husam-Jenidi** [comment]
the design is done on figma, there is another task to import them into godot
