### ISSUE TITLE
Implement exit game on in-game screens

### ISSUE THREAD

**Issue by ilmercu** [Option7-OctoPuss/MeetYourTesterGame#106]
# US: Exit the game [#34](https://github.com/Option7-OctoPuss/MeetYourTesterGame/issues/34)

## PREREQUISITES:
1. UI Prompt confirmation must exists 

## GODOT:
1. Implement the logic behind the press of Escape button
    1. pause the current state of the game
    2. pause possible sound effects (only clickable hexagon) 
    3. emit a signal notifying the game to spawn the confirmation prompt

## BOUNDARIES:
1. What this task handles is the implementation, by emitting a signal, of the logic of the Escape button pressure

## OUTCOMES:
1. Emit exit the game signal

**Comment by FilippoSiri** [comment]
Missing tests and disabling hover on hexagons
