### ISSUE TITLE
Implement Result of Missed Deadline

### ISSUE THREAD

**Issue by Spacekido** [Option7-OctoPuss/MeetYourTesterGame#122]
PREREQUISITES:

Deadlines and Sabotage Button are imported and their logic is working.

GODOT LOGIC:

- When the trigger for a missed deadline activates.
- The sabotage button receives one charge.

BOUNDARIES:

What this tasks handles is adding charges to the sabotage button when deadline is missed.

What this tasks does not handle any other deadline or sabotage button feature.

OUTCOMES:

The sabotage button is charged and clickable when its conditions are satisfied.

**Comment by Siponek** [comment]
@Andrew0133 and me we spent 11h on refactoring of the code. So this task has not been even moved
