### ISSUE TITLE
Create UI for tutorial Scene

### ISSUE THREAD

**Issue by Wh0ll** [Option7-OctoPuss/MeetYourTesterGame#127]
# US: User-Centered Tutorial and Onboarding Experience [#35 ](https://github.com/Option7-OctoPuss/MeetYourTesterGame/issues/35)

## PREREQUISITES:
- none

## FIGMA:
1. Create the UI for the tutorial sceen. The UI created on figma should explain clearly all the steps that the user will take during the tutorial.

## BOUNDARIES:
1. What this task handles is the creation of the UI of the tutorial screen.

## OUTCOMES:
1. Tutorial screen UI

**Comment by Husam-Jenidi** [comment]
The assests are ready to be exported, contact @Matteh15  or @Husam-Jenidi  if you have a problem
This docs file contains the text of the instructions messages.
https://docs.google.com/document/d/1ObSEclQNXsECMd1EZVxnzP8hzin6aHsLG3AOPk5dhVs/edit?usp=sharing
