### ISSUE TITLE
Import UI of the button used to start tutorial and development

### ISSUE THREAD

**Issue by Wh0ll** [Option7-OctoPuss/MeetYourTesterGame#130]
# US: User-Centered Tutorial and Onboarding Experience [#35 ](https://github.com/Option7-OctoPuss/MeetYourTesterGame/issues/35)

## PREREQUISITES:
1. Button for tutorial UI exists

## GODOT:
1. Import the UI on Godot of the tutorial button
2. Implement the change of scenary to the tutorial scene but mantaing also the game state saved, so that the user is able to go back to the game without losing any progress.

## BOUNDARIES:
1. This task handles the implementation in godot of the button UI.

## OUTCOMES:
A functional button that open the tutorial and doesn't cause the loss of game progress.

**Comment by Husam-Jenidi** [comment]
Maybe it can be done as an overlay in order not to lose the game state

**Comment by Siponek** [comment]
![Image](https://github.com/Option7-OctoPuss/MeetYourTesterGame/assets/91413093/c440f7d4-9b68-404f-9ced-1ee254e989e2)
