### ISSUE TITLE
Import in Godot and implements logic of tutorial progress Indicator UI

### ISSUE THREAD

**Issue by Matteh15** [Option7-OctoPuss/MeetYourTesterGame#132]
# US: User-Centered Tutorial and Onboarding Experience [#35 ](https://github.com/Option7-OctoPuss/MeetYourTesterGame/issues/35)

## PREREQUISITES:
1. Tutorial Progress Indicator UI exists
2. Tutorial Scene alredy implemented in Godot

## GODOT:
1. Import the UI on Godot of the Progress indicator UI
2. Implement the logic and graphics change of the progress bar based on the tutorial

## BOUNDARIES:
1. This task handles the implementation in godot of the progress Indicator UI.

## OUTCOMES:
The tutorial will have visual indication of the progress and steps done in it

**Comment by Husam-Jenidi** [comment]
We don't need a ui indicator, we can do the progress indicator as text inside the messages like 1/5, 2/5..etc
