### ISSUE TITLE
Implement continuous progress bar increment

### ISSUE THREAD

**Issue by Siponek** [Option7-OctoPuss/MeetYourTesterGame#25]
**Estimation 8 hours** 

PREREQUISITES:

You need to have the actual node with the assets for the progress bar
GODOT LOGIC / GODOT UI:

Connect the timer of the game (Suggestion: Time in seconds from the Global store, careful of datetime types)
Each time the time changes the progress bar updates by a steady value
This value can be modified further with some modification like difficulty level
It fills up with the fill texture (Suggestion: ProgressBar/TextureProgressBar node)
Handle the overfill, so it does not progresses further. It should generate an event (Suggestion: Print GAME OVER / BAR IS FINISHED to the console)
BOUNDARIES:

What this tasks handles is the continuous increment
What this tasks does not handle updates that are not based on time/timer
OUTCOMES:

Progress bar that when the game starts it also starts to fill up.
It stops filling up when the whole space in the bar is taken.

**Comment by Husam-Jenidi** [comment]
[ProgressBar — Godot Engine (stable) documentation in English](https://docs.godotengine.org/en/stable/classes/class_progressbar.html)
[Godot 4 Master the Progress Bar (pt 1) in 90 Seconds Quick Godot Tutorial (youtube.com)](https://www.youtube.com/watch?v=1gHMG_WuDZY)
