### ISSUE TITLE
Specify the selected answer progress bar impact

### ISSUE THREAD

**Issue by Husam-Jenidi** [Option7-OctoPuss/MeetYourTesterGame#29]
**Estimation: 5hours**
PREREQUISITES:

Have the value of the selected answer stored.

Have the visualized parameters implemented and displayed. (Progress bar API)

GODOT LOGIC / GODOT UI:

Implement the logic of the system of applying the impact:

Check if the value is for future or instant affection.

Store the value of impact in case of future affection.

Different values have different impact on the system parameters

Calculate the impact amount and to what parameter should be added.

Connect the impact with the methods created by task #60 and task #61 to update the progress bar or zones accordingly.

BOUNDARIES:

This task doesn’t directly update the progress bar or zones.

This task stores the future modification value

This task doesn’t consider future modifications (Future states)

OUTCOMES:

The progress bar is ready to get the modification value to be updated.

The future affection is stored to be implemented and timed.

**Comment by Spacekido** [comment]
Here "future effect" is intended as creating a progress bar zone that in the future will alter the bar speed when inside it
