### ISSUE TITLE
US: Deadline Events Generation

### ISSUE THREAD

**Issue by Siponek** [Option7-OctoPuss/MeetYourTesterGame#37]
# **Front / Description:**

As a player,
I want to see projects deadlines which represent phases/sprints/deliverables of development,
So I can make decisions how to sabotage the project by preventing the progress bar from reaching its deadlines.

I want the game to show where the deadlines are on the progress bar and how much time they have left before they are missed.

# **Back / Acceptance Criteria:**

## Scenario: User identifying deadlines

- Given the game is in progress,
- When the player begins their session,
- Then all deadlines are clearly shown to the player on the progress bar, including a countdown for the time remaining until each deadline is missed.

## **Scenario: User misses a deadline**

- Given the player is in game session,
- When the deadline is not reached by the progress bar in time,
- Then the deadline is marked as sabotaged 
- And its countdown will be disabled

## **Scenario: User reaches a deadline in predetermined time**

- Given the player is in game session,
- When the deadline is reached by the progress bar in predetermined time,
- Then the deadline is marked as delivered/success 
- And its countdown will be disabled

## **Scenario: Tracking missed and reached deadlines**

- Given the player is in game session at any time,
- Then all deadlines are clearly shown on the progress bar
- And their status  updated in real-time.

**Comment by Siponek** [comment]
This is an Epic, should be split

**Comment by Spacekido** [comment]
Optional feature: when the progress bar increase of answer would move the bar over a deadline, instead stop it at the deadline which is then marked as reached.
This acts as a lifeguard against skipping too much.

**Comment by Spacekido** [comment]
Use this as guide for the design and logic

![Image](https://github.com/Option7-OctoPuss/MeetYourTesterGame/assets/65166968/6ba3b685-2637-44b0-b840-07da4c2ffa8f)
