### ISSUE TITLE
US: Anonymity Bar and Sabotage Button

### ISSUE THREAD

**Issue by Siponek** [Option7-OctoPuss/MeetYourTesterGame#42]
# **Front / Description:**

As a **player**, I want to use the Anonymity Bar as a strategic resource. 
By activating the Sabotage Button, I can spend one of its charges and some points from the anonymity bar in order to decrease the countdown of the final deadline, so I can win the game faster.

The Sabotage Button can be activated only if it has at least one charge, which is gained by missing deadlines on the progress bar. 

The Sabotage Button should show its cost in anonymity points.

# **Back / Acceptance Criteria:**

## Scenario: Activating the sabotage button

**Given** the sabotage button has at least one spendable charge and enough anonymity value,
**When** the player presses the button,
**Then** the countdown of the final deadline is decreased by some time,
**And** the charge and the anonymity cost are spent.

## Scenario: Cannot activate the sabotage button

**Given** the anonymity value isn't high enough to activate the button,
**Then** the button is disabled and cannot be pressed.

**Comment by Siponek** [comment]
Additional Ideas for the Anonymity Bar:

**Cooldown Reduction**: Using Anonymity points to reduce the cooldown on critical sabotage abilities, allowing for more frequent use.

**Invisibility Spike**: Temporarily increasing the Anonymity level to maximum, making the player's actions untraceable and ensuring that risky moves don't decrease the Anonymity Bar for a short period.

**Information Leak**: Players can spend Anonymity points to "leak" false information, causing confusion and slowing down the project's progress as NPCs spend time addressing the fabricated issues.

**Trust Manipulation**: Temporarily boost the effect of positive actions on stakeholder patience or team morale by appearing more trustworthy, thus allowing for more aggressive sabotage without raising suspicions.

**Sabotage Insight**: Spend Anonymity to gain insight into the most impactful sabotage opportunities coming up, allowing the player to plan their actions around these events for maximum effect.

**Comment by Spacekido** [comment]
Optional feature:
when the anonymity bar goes under a certain level, then the level is locked and it cannot go back over it again.
