### ISSUE TITLE
Read up on possible tests that can be done on the Business Logic

### ISSUE THREAD

**Issue by Spacekido** [Option7-OctoPuss/MeetYourTesterGame#49]
# US: Scenario for Business Logic
## DOCS:

- Research possible testing strategies and types that relate to the Business Logic domain of an application
- Create a brief report with links to resources 

## BOUNDARIES:

What this task handles is to create a report about testing strategies and types for the Business Logic
What this tasks does not handle is writing any scenario content

## OUTCOMES:

The report is created and available

**Comment by Wh0ll** [comment]
https://docs.google.com/document/d/18RTRgqD_6WIXSgfykVJw6JRTQnaTqKKAEgPWuWSNOLg/edit#heading=h.o981i3pp4iy0
