### ISSUE TITLE
Read up on possible tests that can be done on the UI/UX

### ISSUE THREAD

**Issue by Spacekido** [Option7-OctoPuss/MeetYourTesterGame#50]
# US: Scenario for UI/UX user testing

## DOCS:

- Research possible testing strategies and types that relate to the UI/UX domain of an application
- Create a brief report with links to resources 

## BOUNDARIES:

What this task handles is to create a report about testing strategies and types for the UI/UX
What this tasks does not handle is writing any scenario content

## OUTCOMES:

The report is created and available

6hours

**Comment by Siponek** [comment]
The task was _**(Probably)Finished**_ in 3h
