### ISSUE TITLE
Write and implement scenario: UI/UX

### ISSUE THREAD

**Issue by Spacekido** [Option7-OctoPuss/MeetYourTesterGame#51]
# US: Scenario for UI/UX user testing

## TEXT / GODOT:

- Write (at least 3) questions about this scenario
- Write the possible answers for each question about this scenario
  - some negative examples could be:
    * Misguiding testers with irrelevant tasks.
    * Prioritizing form over function, leading to usability issues.
    * Ignoring user feedback on critical bugs.
  - some positive examples could be:    
    * Streamlining the testing process.
    * Focusing on high-impact bugs.
- Attribute relative game effects to each answer, following the defined format
- Import the questions and the answers in godot as JSON file

## BOUNDARIES:

This task handles writing the scenario's question and answers with effects, and import them in Godot.
This task doesn't handle any other scenario.

## OUTCOMES:

The questions and answers with game effects for the UI/UX scenario are imported and selectable in the game
3hours

**Comment by Siponek** [comment]
Only implementing the question into Godot remains
