### ISSUE TITLE
Write and implement scenario: Business Logic

### ISSUE THREAD

**Issue by Spacekido** [Option7-OctoPuss/MeetYourTesterGame#52]
# US: Scenario for Business Logic
## PREREQUISITES:

- Task:  **Read up on possible tests that can be done on the Business Logic**

## TEXT / GODOT:

- Write (at least 3) questions about this scenario
- Write the possible answers for each question about this scenario
  - some negative examples could be:
    * Writing test cases with too few inputs.
    * Writing test following exhaustive testing approach when there are too many combinations of input (i.e. testing form).
    * Decide wrong bounds in Boundary Testing
    * Hardcoding test data directly into tests rather than using dynamic or randomized data can lead to predictable tests that may not catch unexpected behavior.
  - some positive examples could be:    
    * Pairwaise or Boundary Testing.
    * Incorporate performance testing to assess the scalability and efficiency of the business logic under different load conditions, helping identify potential performance bottlenecks early on.
- Attribute relative game effects to each answer, following the defined format
- Import the questions and the answers in godot as JSON file

## BOUNDARIES:

This task handles writing the scenario's question and answers with effects, and import them in Godot.
This task doesn't handle any other scenario.

## OUTCOMES:

The questions and answers with game effects for the Business Logic scenario are imported and selectable in the game

**Comment by Husam-Jenidi** [comment]
1.5 hours spent on this

**Comment by Husam-Jenidi** [comment]
Template for the questions:

ActionEvent-Topic-ID: **You are** <given a context> / <during a testing phase> **and** <must pick the testing type>. **How do you** <handle / test> **this behavior**?
**I will** <do something bad because>. (xP,xZ,xA)
**I will** <do something good because>. (xP,xZ,xA)
**I will** <do something passive (ignore) because>. (xP,xZ,xA)

**Comment by Spacekido** [comment]
The difficulty has been removed from questions because too burdensome to apply, can be used later when all questions are done.
