### ISSUE TITLE
Read up on possible tests that can be done on the Database

### ISSUE THREAD

**Issue by Spacekido** [Option7-OctoPuss/MeetYourTesterGame#53]
# US: Scenario for Database 

## DOCS:

- Research possible testing strategies and types that relate to the Database domain of an application
- Create a brief report with links to resources 

## BOUNDARIES:

What this task handles is to create a report about testing strategies and types for the Database
What this tasks does not handle is writing any scenario content

## OUTCOMES:

The report is created and available

**Comment by Wh0ll** [comment]
https://docs.google.com/document/d/14K8YUAhzp-GYfvAYce_6YY6qaeF2MDHSb2cLJUzsT64/edit

**Comment by Spacekido** [comment]
Moved to unified docs file with other reports
