### ISSUE TITLE
Read up on possible tests that can be done on the Delivery

### ISSUE THREAD

**Issue by Spacekido** [Option7-OctoPuss/MeetYourTesterGame#57]
# US: Scenario for Delivery

## DOCS:

1. Read up on possible tests that can be done on the Delivery of the application;
2. Write a report about testing strategy and types

## BOUNDARIES:

1. What this task handles is to write a report about testing strategy and types for the Delivery.
2. What this tasks does not handle is to write the questions for the game

## OUTCOMES:

1. The report

**Comment by FilippoSiri** [comment]
https://docs.google.com/document/d/1hGU9eq0benvJPUHN_yZcJ3sIiJXXpI2cPaR2lPCIt3o/edit?usp=sharing
