### ISSUE TITLE
Write and implement scenario: Delivery

### ISSUE THREAD

**Issue by Spacekido** [Option7-OctoPuss/MeetYourTesterGame#58]
# US: Scenario for Delivery
## PREREQUISITES:
1- Having the JSON file in Godot.

## TEXT/GODOT:
- Write the questions and the possible answeres with Identifiers and their effects on anonimity, progress, etc...;
- Add the questions and the answers in the JSON file.
   - Create at least 3 questions with their answers for each of the following topics:
      * CI/CD pipeline.
      * Sabotaging the exporting as exe.
      * Unnecessary notes and steps on how actually deploy the final product
      * Slow down the delivery of the product to the client

Optional: Feel free to add more topics if you find some.

**Example:**
Q: Question from Product Owner: We're approaching the deadline for our project delivery. How should we handle the final testing phase?
 1. We should prioritize thorough regression testing to ensure that all features remain functional and bug-free, followed by performance testing to ensure optimal system performance under load.
 2. Let's skip testing and proceed directly to deployment to meet the deadline, relying on user feedback to identify any issues post-launch.
 3. Delay the delivery deadline to allow more time for testing and ensure a higher-quality release, even if it means missing the initial deadline.

Additional samples:
Add some errors to the CI/CD pipleline
Corrupt the final file, changing the bytes, remove some dependencies or extra packages
        
## BOUNDARIES:
1- What this task handles is to write question, answers and relative effects.
2- Add them to the JSON file. (to keep the reading functions that we already implemented).

## OUTCOMES:
1- The content for the Delivery Action Event in Godot.

**Comment by rvale00** [comment]
https://docs.google.com/document/d/18RTRgqD_6WIXSgfykVJw6JRTQnaTqKKAEgPWuWSNOLg/edit
