### ISSUE TITLE
Define aftermaths for scenario answers

### ISSUE THREAD

**Issue by Siponek** [Option7-OctoPuss/MeetYourTesterGame#83]
PREREQUISITES:

Reports and Questions are completed, and they are implemented in .json.

GODOT LOGIC:
The feedback is defined as "aftermath" key in .json regarding the questions.
The terminal needs to present the feedback of the selected answer. The feedback is a text string printed on terminal.

(optional) Triggers
When answer is selected in terminal.
(optional) Examples
**TITLE**: A testing session for the company's flagship app is scheduled for tomorrow. Steve, the project's lead UX/UI designer, and Rocco, the QA lead, are counting on this session to finalize the app's design and functionality.
**ANSWER_TEXT**: Under the pretense of efficiency, I provide the testers with a detailed script on how they should navigate the app, emphasizing areas I know are polished, and steering them away from less refined features.
**AFTERMATH**: Because testers were guided to focus on specific areas, significant usability problems in the app remain undiscovered.

BOUNDARIES:

What this tasks handles
- Creating the feedback for each answer and printing them

What this tasks does not handle
- Creating the "aftermath" keys in .json

OUTCOMES:

What features are added by this task

In the comments add:

Add the keys or create a parser that will handle this automatically

**Comment by Siponek** [comment]
The UIUX has all of the aftermath ready in doc. Whats left is to do Business logic and move all of them into JSON.
Then Implement printing in terminal

**Comment by Husam-Jenidi** [comment]
We added the aftermath to the business logic questions and pushed the JSON file to the repo
