### ISSUE TITLE
Search sound effects and musics online

### ISSUE THREAD

**Issue by ilmercu** [Option7-OctoPuss/MeetYourTesterGame#97]
# US: Game background sound and effects [#89](https://github.com/Option7-OctoPuss/MeetYourTesterGame/issues/89)

## PREREQUISITES:
None

## GODOT:
- Search for free copyright music for:
    - background music

- Search for free copyright sound effects for:
    - clickable hexagon effect
    - clicked hexagon effect
    - clicked answer

## BOUNDARIES:
1- What this task handles is to search and download music and sound effects for the game importing them also on godot project

## OUTCOMES:
1- Music files in the godot project

**Comment by Husam-Jenidi** [comment]
When picked, discuss all the sounds you might need
